// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

// Configuration that works with rustc < 1.71.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    netflix
    (
        init => init
        setSafePriceView => set_safe_price_view
        addToken => add_token
        addService => add_service
        setSubscriptionAddress => set_subscription_address
        getSubscriptionsTokens => get_subscription_tokens
        initServicesCount => init_services_count
        initTokensCount => init_tokens_count
        getTokensCount => tokens_count
        getTokens => tokens
        getLPAddress => lp_address
        getServicesCount => services_count
        getServices => services
        getSafePriceView => safe_price_view
        getSubscriptionAddress => subscription_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
